[general]
import = [
    "~/.config/alacritty/themes/dracula/dracula.toml",
]

[window]
dimensions = { columns = 120, lines = 30 }
position = { x = 100, y = 100 }
padding = { x = 15, y = 10 }
decorations = "full"
startup_mode = "Windowed"
dynamic_title = true
opacity = 0.95

[font]
size = 12.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

[terminal]

[colors]

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
]

[cursor]
style = "Block"
unfocused_hollow = true

[selection]
save_to_clipboard = true
